<a href="https://colab.research.google.com/github/dbwhdgjs/2026-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a=np.ndarray((2,3))
a

array([[2.46356794e-315, 0.00000000e+000, 0.00000000e+000],
       [3.49848756e-205, 1.38261736e-316, 1.38258698e-316]])

In [3]:
import numpy as np

a=np.ndarray((3,2), dtype= int)
a

array([[          498631703,                   0],
       [                  0, 1548134894717108224],
       [           27984487,            27983872]])

In [4]:
import numpy as np
a= np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [7]:
print(a.size)
print(a.itemsize) # 배열 내 요소가 차지하는 바이트 단위, int64 -> 64비트 -> 8바이트
print(a.nbytes) # 일반적으로 size * itemsize.

3
8
24


In [8]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [10]:
import numpy as np
unicode_array = np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [11]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [12]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [13]:
import numpy as np
print(np.arange(2.0))
print(np.arange(2.0 , 6.5))

print(np.arange(2.0 , 6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [14]:
import numpy as np

a=np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.reshape(a,(2,6))


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [16]:
np.reshape(a,(3,5)) # 원소수가 부족하다.

ValueError: cannot reshape array of size 12 into shape (3,5)

In [31]:
import numpy as np

a=np.array([1,2,3,4,5,6])
a.reshape(2,3).shape # (행, 렬) -> 2차원 3개

(2, 3)

In [17]:
#  np.linspace(start, stop, num)
#  시작값, 끝값, num(점의 개수, 기본값 : 50개)
# 간격 = (stop- start) / (num-1)

In [18]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [20]:
np.linspace(2.0, 3.0, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [22]:
print((3-2)/(50-1)) # 간격구하기 수식

0.02040816326530612


In [26]:
np.linspace(2.0, 3.0, endpoint = False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [27]:
print((3-2)/50)

0.02


In [28]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [29]:
np.linspace(2.0,3.0,num=5,endpoint = False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [32]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [33]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [35]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:

np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.eye(3) # 단위행렬(가운데 대각선 만 1인 행렬)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [40]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [41]:
a= np.eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
b = np.eye(3,4,-1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [43]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [44]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [46]:
np.full([2,3],(1,2)) # 원소수 부족

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [47]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [49]:
np.full([4,3],fill_value = np.arange(4).reshape(4,1)) # ⭐️

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [51]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [52]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [53]:
np.empty([2,3],dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

In [54]:
import numpy as np

a= np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [60]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [61]:
import numpy as np

a= np.arange(3)
a


array([0, 1, 2])

In [62]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [64]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
b=np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [68]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [70]:
# [2, 3] @ [3, 3] -> @ :곱셈연산자, 앞 차원의 뒷 숫자와 뒤차원의 앞 숫자가 같아야 연산됨.

In [89]:
import numpy as np
a = np.full((2,3),[1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [90]:
b=np.full((3,2),[2.1])
b

array([[2.1, 2.1],
       [2.1, 2.1],
       [2.1, 2.1]])

In [91]:
a@b

array([[12.6, 12.6],
       [12.6, 12.6]])

In [92]:
a.dot(b)

array([[12.6, 12.6],
       [12.6, 12.6]])

In [93]:
b.dot(a)

array([[ 4.2,  8.4, 12.6],
       [ 4.2,  8.4, 12.6],
       [ 4.2,  8.4, 12.6]])

In [94]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12.6 12.6]
 [12.6 12.6]]
[[ 4.2  8.4 12.6]
 [ 4.2  8.4 12.6]
 [ 4.2  8.4 12.6]]


In [96]:
a=np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [97]:
a.sum()

np.int64(46)

In [102]:
a.sum(axis=0) # 열 합 배열

array([16, 30])

In [103]:
a.sum(axis=1) # 행 합 배열 (시험 ⭐️)

array([30, 13,  3])

In [104]:
import numpy as np
print(np.sum(a))
print(np.sum(a ,axis=0))
print(np.sum(a ,axis=1))

46
[16 30]
[30 13  3]


In [105]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [109]:
a.cumsum() # 일차원으로 펼쳐서 계속 합해주기

array([ 3,  8, 16, 17, 19, 22])

In [111]:
a.cumsum(axis=0) # 각 열에 대한 합

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [112]:
a.cumsum(axis=1) # 각 행에 대한 합

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [113]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [114]:
b = np.full_like(a,2)
b

array([2, 2, 2])

In [115]:
np.add(a,b)

array([ 3,  6, 11])

In [116]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [117]:
np.power(a,b)

array([ 1, 16, 81])

In [118]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [120]:
print(a[3])
print(a[-2])

9
64


In [121]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [122]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [123]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [124]:
a[::-2]

array([81, 49, 25,  9,  1])

In [126]:
a[2:5]=-100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [128]:
a[2:5]=[-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [130]:
a[2:5] = [-5,-5] # 원소 부족
a


ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [131]:
a[2:5]=-10
a


array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [132]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [133]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [134]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [135]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [136]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [137]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [138]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [140]:
a[, 1] # 비우면 오류

SyntaxError: invalid syntax (880823167.py, line 1)

In [141]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [142]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [143]:
a= np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [144]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [145]:
a[2,4]

np.int64(16)

In [146]:
a[2][4]

np.int64(16)

In [147]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [148]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [149]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [150]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [153]:
a[::-1, ::-1] # 행 열 모두 역순으로 바꿈 ⭐️

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [154]:
a[:-1, :-1] # 행과 열세어 마지막을 제거 ⭐️

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [157]:
a= np.arange(24).reshape(2,3,4) # 2개, 3행 4열
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [158]:
a[0] # axis=0 의 0번

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
a[1] # axis=0의 1번 -> 2번째 배열

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [160]:
a[:,1] # axis=0의 모든 배열 중 axis=1 축에서 첨자 1번

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [162]:
a[:, 1, 1] # axis=0의 모든 배열중 위치 (1,1)

array([ 5, 17])

In [163]:
a[:, :, 1] # 마지막축인 axis= 2의 철자가 1인 배열

array([[ 1,  5,  9],
       [13, 17, 21]])

In [164]:
a[...,1] # a[:, :, 1]과 동일, ... = 해당되는 축이 모두 : 인것을 의미.

array([[ 1,  5,  9],
       [13, 17, 21]])

In [165]:
a[1, ..., 1]

array([13, 17, 21])

In [168]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [171]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [173]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [174]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [175]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [262]:
b= np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [263]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [264]:
np.transpose(b,(0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [265]:
np.transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [266]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [267]:
x=np.array([[7,8,9]])
x

array([[7, 8, 9]])

In [269]:
y=np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [270]:
y=np.swapaxes(x,1,0)
y

array([[7],
       [8],
       [9]])

In [271]:
y[0,0]=10
x

array([[10,  8,  9]])

In [273]:
x=np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [274]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [275]:
np.transpose(x,(2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [276]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [277]:
v=org.view()
v

array([0, 1, 2, 3, 4])

In [278]:
v[2]=200
v

array([  0,   1, 200,   3,   4])

In [279]:
org

array([  0,   1, 200,   3,   4])

In [280]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [281]:
c=org.copy()
c

array([0, 1, 2, 3, 4])

In [283]:
c[2]=200
c

array([  0,   1, 200,   3,   4])

In [284]:
org

array([0, 1, 2, 3, 4])

In [285]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [286]:
y=x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [287]:
print(x.base)

None


In [288]:
y.base

array([0, 1, 2, 3, 4, 5])

In [289]:
z=y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [290]:
c=z.copy()
print(c.base)

None


In [291]:
lst=list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [292]:
lst[3:5]=[30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [293]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [294]:
x[3:5]=[30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [295]:
x[3:5]=[30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [296]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [297]:
b=a
b is a

True

In [298]:
print(id(a))
print(id(b))

139369772712560
139369772712560


In [299]:
print(a.base)
print(b.base)

None
None


In [300]:
b[0, 0]=100

In [301]:
c=a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [302]:
print(id(a))
print(id(c))

139369772712560
139369772721488


In [303]:
print(c.base)

None


In [304]:
v= a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [305]:
print(id(a))
print(id(v))

139369772712560
139369772713232


In [307]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [308]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [309]:
a=np.array([3,4,5,7])
b=np.array([8,7,6])
a*b # 배열이 달라 연산 X

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [310]:
from numpy import arange
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [311]:
y=arange(-1,2)

In [312]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [313]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [314]:
from numpy import arange
x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [315]:
y= arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [316]:
np.set_printoptions(precision=2) # 소수점 이하 자릿수를 2자리로 설정

In [317]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [318]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [319]:
from numpy import arange
x=arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [320]:
y=arange(1,3)
y

array([1, 2])

In [321]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [322]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [323]:
import numpy as np
from numpy import array
x=array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [324]:
np.newaxis is None

True

In [325]:
a=x[None, :] # (4, ) 에서 (1, 4) 가 됨.
a

array([[ 0, 10, 20, 30]])

In [326]:
# [1,2,3,4] - > (4,)
# [[ 1,2,3,4 ]] -> [1,4]

In [327]:
a= x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [328]:
a= x[:,np.newaxis] # (4, ) 에서 (4, 1) 이됨
a

array([[ 0],
       [10],
       [20],
       [30]])

In [329]:
a.shape

(4, 1)

In [330]:
from numpy import array
b=array([1,2,3])
b

array([1, 2, 3])

In [331]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [332]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

# 고급 색인

In [333]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [334]:
x[1]

np.int64(1)

In [335]:
x[:5]

array([0, 1, 2, 3, 4])

In [336]:
print(x[[1]])

[1]


In [337]:
print(x[[2,3]])

[2 3]


In [338]:
x[[1,1,2,5]]

array([1, 1, 2, 5])

In [339]:
x[[1,1,2,5,-1,-2,-5]]

array([1, 1, 2, 5, 9, 8, 5])

In [340]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [341]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [342]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [343]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [344]:
x[0,1]

np.int64(1)

In [345]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [346]:
x[, 2:8] # 축 0을 비우면 오류

SyntaxError: invalid syntax (3682451689.py, line 1)

In [347]:
x[[0],[1]]

array([1])

In [348]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [349]:
x[:,[5,4]] # 행은 모두 출력, 열은 5열, 4열 순으로 출력.

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [350]:
x[[1,3]] # 1열 ,3열만 1~3으로 헷갈리지말기.

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [351]:
x[[1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [352]:
from numpy import arange
x=arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [353]:
x[[1,3],[2,2]]

array([10, 26])

In [354]:
x[[1,3],[2]]

array([10, 26])

In [355]:
x[[1,3],2]

array([10, 26])

In [356]:
from numpy import arange

x=arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [357]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [358]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [359]:
x[array([0,2,4]),:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [360]:
from numpy import array

x[array([0,2,4]),array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [361]:
from numpy import arange
a=arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [362]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [363]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [364]:
a[arange(2,4)][:, [1,0]]

array([[17, 16],
       [25, 24]])

In [365]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [366]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [367]:
np.arange(-1,-8,-1)

array([-1, -2, -3, -4, -5, -6, -7])

In [368]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])